pipeline:
  identifier: Build_ruby_sample_1709280093351
  name: Build ruby-sample
  orgIdentifier: default
  projectIdentifier: RaghavTest
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: false
          execution:
            steps:
              - step:
                  identifier: bundleinstall
                  name: bundle_install
                  spec:
                    shell: Sh
                    command: echo <+matrix.ip>
                  timeout: ""
                  type: Run
                  strategy:
                    matrix:
                      ip:
                        - 12
                        - 13
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          caching:
            enabled: false
            paths: []
        type: CI
        description: ""
